### PR TITLE
New shader

### PR DESCRIPTION
**Pull request by igorrafael**

### CODE REVIEW

**Comment by unitycoder** [comment]
btw. does this allow you to merge it yourself? (as you are member)

**Comment by igorrafael** [comment]
It doesn't. Also tried pushing directly but it seems that I don't have
write access. You should be able to change that somewhere though :)

**Comment by unitycoder** [comment]
ok how about now? By default it had Read only access for members..

**Comment by igorrafael** [comment]
Worked, thanks.

**Pull request merged**
